# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins: ["jekyll-paginate", "jekyll-gist"]

# Permalinks
permalink:        pretty

# Setup
title:            Learn Foundations Internship 2025
tagline:          'An Internship Journal'
description:      "A digital journal of my experince as an intern at The University of Edinburgh's Information Services Group"
url:              http://juliaconey.github.io/
baseurl:          /juliaconey.github.io/

author:
  name:           'Julia Coney'
#  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
# repo:           https://github.com/poole/hyde
  me: http://juliaconey.github.io/
